name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout sources and Push tags
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '16.5'
          msbuild-architecture: x64
      - name: Build binary files
        run: |
          cmd
          mkdir native\build
          cd native\build
          cmake ..
          msbuild native.vcxproj /p:configuration=release
          msbuild native.vcxproj /p:configuration=debug
          cd ..\..
          mkdir dest
          mkdir dest\Release
          mkdir dest\Debug
          copy native\build\Release\* dest\Release
          copy native\build\Debug\* dest\Debug
          copy native\build\Release\* .
          gradlew build
          copy build\libs\* dest
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        run: 
        with:
          name: build_${{github.sha}}
          path: ${{ github.workspace }}\dest
